# This is an example of the config file that you should create in the path src/config/config.yaml
# You can copy this file and paste it in the path src/config/config.yaml
# Then you can modify the values to your needs

# General config values
llm_model: chatgpt # gemini or chatgpt
sql_motor: pandasql
table_name: df

# Config Values Gemini
gemini_api_key: API_KEY
gemini_model: gemini-2.0-flash-lite # gemini-2.0-flash  gemini-2.0-flash-lite

# Config Values ChatGPT
chatgpt_api_key: API_KEY
chatgpt_model: gpt-3.5-turbo # gpt-4  gpt-3.5-turbo-16k  gpt-3.5-turbo

#Hyperparameters
default_context: Eres un generador experto de consultas SQL y estas dentro de una aplicacion de python".
temperature: 0.5
max_output_tokens: 1024
top_p: 0.5
top_k: 40
